export interface FallbackCrossword {
  grid: string[];
  acrossClues: string[];
  downClues: string[];
}

export const CROSSWORD_FALLBACKS: FallbackCrossword[] = [
  {
    grid: [
      "CAME#PLANT#DESK",
      "OVER#GHOST#RULE",
      "WIDE#BRAIN#EAST",
      "SUGAR#AND#OCEAN",
      "##HIT#USE#OLD##",
      "EARTH#AGE#BLANK",
      "TIN#CAPABLE#ART",
      "SET#RAINBOW#NEW",
      "MAP#KITCHEN#TOY",
      "GRAPE#AIM#SHELF",
      "##AGE#PIN#ACE##",
      "ANGLE#OAR#TOWER",
      "MENU#STORE#ABLE",
      "ACID#TRAIL#KNEE",
      "PILE#ATLAS#YELL",
    ],
    acrossClues: [
      "Arrived", "Flora", "Writing surface",
      "Above", "Phantom", "Regulation",
      "Broad", "Organ of thought", "Sunrise direction",
      "Sweet substance", "Plus", "Large body of water",
      "Strike", "Employ", "Not new",
      "Our planet", "Era", "Empty",
      "Metal container", "Competent", "Creative work",
      "Group", "Colorful arc", "Fresh",
      "Chart", "Cooking room", "Plaything",
      "Wine fruit", "Target", "Storage ledge",
      "Time period", "Fastener", "Top card",
      "Geometric figure", "Rowing tool", "Tall structure",
      "Food list", "Shop", "Capable",
      "Sour substance", "Path", "Leg joint",
      "Stack", "Book of maps", "Shout",
    ],
    downClues: [
      "Bovine animals", "Compass letters", "Long thread",
      "Winding path", "Hidden words", "Central section",
      "Quick note", "Brief pause", "Final act",
      "Continuous line", "Unbroken chain", "Straight ahead",
      "Small unit", "Middle part", "End piece",
      "Extended run", "Opening move", "Closing scene",
      "Full range", "Brief look", "Quick step",
      "Short stop", "Inner circle", "Distant view",
      "End note", "Ground level", "Last word",
      "Far reach", "Deep thought",
    ],
  },
  {
    grid: [
      "WARM#STONE#FIRE",
      "IDEA#HONEY#OPEN",
      "NEST#EVENT#RIDE",
      "TOWER#AGO#CREAM",
      "##MAP#RUN#OAK##",
      "FRAME#DIM#SLEEP",
      "OWL#CHAMBER#AGE",
      "PEN#CAPTAIN#USE",
      "ERA#BALANCE#THE",
      "PLANT#RAN#STARE",
      "##APE#OWE#TIN##",
      "MUSIC#TAP#BRAVE",
      "CAKE#WORLD#LEND",
      "AXIS#UNITE#AREA",
      "BEST#DENIM#YAWN",
    ],
    acrossClues: [
      "Heated", "Rock", "Blaze",
      "Concept", "Bee product", "Not closed",
      "Bird home", "Occurrence", "Horse trip",
      "Tall structure", "In the past", "Dairy treat",
      "Chart", "Sprint", "Strong tree",
      "Border", "Faint", "Slumber",
      "Night bird", "Grand room", "Time period",
      "Writing tool", "Ship leader", "Employ",
      "Historical period", "Equilibrium", "Article",
      "Greenery", "Moved fast", "Gaze fixedly",
      "Primate", "Be in debt", "Metal can",
      "Melodies", "Light touch", "Courageous",
      "Sweet dessert", "Earth", "Give temporarily",
      "Symmetry line", "Join together", "Zone",
      "Greatest", "Jeans fabric", "Sleepy stretch",
    ],
    downClues: [
      "Column sequence", "Vertical fill", "Cross pattern",
      "Read across", "Letter run", "Mixed column",
      "Down fill", "Intersecting", "Grid column",
      "Crossing path", "Vertical word", "Through line",
      "Shared letters", "Column hint", "Check across",
      "Letter column", "Down sequence", "Pattern fill",
      "Crossing word", "Column entry", "Grid fill",
      "Vertical line", "Cross letters", "Through path",
      "Down entry", "Linked column", "Mixed letters",
      "Down run", "Column pattern",
    ],
  },
  {
    grid: [
      "BOLD#GRACE#MINE",
      "AREA#LIMIT#AXIS",
      "RAIN#INNER#DARK",
      "SENSE#LOG#BEACH",
      "##PIG#OAT#HIT##",
      "STEEL#BOW#OPERA",
      "LEG#BLANKET#MOB",
      "ATE#COMBINE#OWE",
      "PEN#SILENCE#RED",
      "BLAME#OAR#ARROW",
      "##ICE#DAM#TEN##",
      "COMET#SPA#DRIVE",
      "HAZE#CLOUD#SOFA",
      "ACID#LUNAR#EVEN",
      "TOSS#ESSAY#DENY",
    ],
    acrossClues: [
      "Daring", "Elegance", "Excavation",
      "Zone", "Boundary", "Pivot line",
      "Precipitation", "Inside", "Without light",
      "Feeling", "Timber piece", "Sandy shore",
      "Farm animal", "Cereal grain", "Strike",
      "Alloy metal", "Weapon or knot", "Musical drama",
      "Limb", "Warm cover", "Crowd",
      "Consumed", "Merge", "Be in debt",
      "Writing tool", "Quiet", "Color",
      "Fault", "Rowing tool", "Pointer",
      "Frozen water", "Barrier", "Number after nine",
      "Space rock", "Resort", "Operate a car",
      "Fog", "Sky mass", "Couch",
      "Sour substance", "Moon-related", "Level",
      "Throw casually", "Written piece", "Refuse",
    ],
    downClues: [
      "Grid crossing", "Letter chain", "Vertical path",
      "Intersecting", "Down pattern", "Column fill",
      "Cross entry", "Linked letters", "Through column",
      "Mixed fill", "Down word", "Crossing point",
      "Column letters", "Vertical run", "Check across",
      "Shared column", "Letter pattern", "Down fill",
      "Cross pattern", "Column entry", "Grid path",
      "Through line", "Vertical fill", "Down sequence",
      "Crossing word", "Column run", "Letter line",
      "Down entry", "Column trail",
    ],
  },
  {
    grid: [
      "DAWN#ORBIT#BLUE",
      "OBOE#NERVE#LAKE",
      "ZERO#IMAGE#ARCH",
      "EAGLE#BOX#CORAL",
      "##HEN#ODD#ATE##",
      "CRISP#DEN#YOUTH",
      "OIL#PILGRIM#ROW",
      "FOX#ITALIAN#OAR",
      "USE#LEATHER#NEW",
      "KNELT#MAD#SAINT",
      "##AGE#AGO#TON##",
      "CRANE#PEW#HOTEL",
      "HOME#PLAZA#GLOW",
      "INCH#ALIVE#RAIN",
      "PALE#ROSES#OMEN",
    ],
    acrossClues: [
      "Sunrise", "Path around", "Sky color",
      "Woodwind", "Courage", "Body of water",
      "Nothing", "Reflection", "Curved structure",
      "Large bird", "Container", "Reef material",
      "Female chicken", "Strange", "Consumed",
      "Crunchy", "Animal lair", "Young age",
      "Liquid fuel", "Traveler", "Boat line",
      "Wild canine", "European", "Rowing tool",
      "Employ", "Hide material", "Fresh",
      "Bent down", "Angry", "Holy person",
      "Time period", "In the past", "Weight unit",
      "Tall bird", "Church seat", "Lodging",
      "Residence", "Town square", "Shine",
      "Small measurement", "Living", "Precipitation",
      "Light color", "Flowers", "Sign of things to come",
    ],
    downClues: [
      "Vertical chain", "Column path", "Grid crossing",
      "Down pattern", "Letter sequence", "Cross fill",
      "Through column", "Intersecting", "Down word",
      "Column letters", "Crossing point", "Vertical entry",
      "Linked column", "Mixed letters", "Down fill",
      "Cross pattern", "Column trail", "Through path",
      "Vertical line", "Letter column", "Grid fill",
      "Down run", "Column entry", "Check across",
      "Letter chain", "Down sequence", "Crossing word",
      "Column fill", "Vertical path",
    ],
  },
  {
    grid: [
      "WISH#FLAME#SAND",
      "ACHE#LUNAR#TREE",
      "STOP#OCEAN#HERO",
      "LIVER#OWE#DRAPE",
      "##PEN#ASH#END##",
      "SPINE#TAB#OASIS",
      "COT#KITCHEN#RAW",
      "AID#IMAGINE#OWL",
      "BED#NURSERY#THE",
      "ANGEL#SET#BRIDE",
      "##RAN#OLD#LEG##",
      "GRAIN#SIT#TEETH",
      "FADE#MAJOR#OVAL",
      "IRIS#ALBUM#VINE",
      "RENT#NASTY#SHED",
    ],
    acrossClues: [
      "Desire", "Fire tongue", "Beach grains",
      "Dull pain", "Moon-related", "Woody plant",
      "Halt", "Vast water", "Brave one",
      "Body organ", "Be in debt", "Curtain fabric",
      "Writing tool", "Fireplace dust", "Finish",
      "Backbone", "Browser marker", "Desert refuge",
      "Small bed", "Cooking room", "Uncooked",
      "Assistance", "Envision", "Night bird",
      "Sleeping place", "Child care room", "Article",
      "Heavenly being", "Group or kit", "Wedding woman",
      "Moved quickly", "Not new", "Body part",
      "Cereal seed", "Be seated", "Chompers",
      "Disappear slowly", "Key or important", "Egg-shaped",
      "Flower or eye part", "Music collection", "Climbing plant",
      "Payment for housing", "Unpleasant", "Small building",
    ],
    downClues: [
      "Cross column", "Vertical word", "Letter run",
      "Down path", "Grid letters", "Intersecting",
      "Column pattern", "Through line", "Down fill",
      "Mixed column", "Crossing word", "Vertical fill",
      "Shared letters", "Down entry", "Column chain",
      "Grid column", "Letter path", "Cross pattern",
      "Down word", "Through column", "Vertical run",
      "Column entry", "Linked letters", "Grid fill",
      "Down sequence", "Cross entry", "Column trail",
      "Vertical path", "Letter column",
    ],
  },
  {
    grid: [
      "LAMP#STARE#GOLF",
      "OPAL#HERON#IDEA",
      "VINE#EXACT#DEBT",
      "EARTH#DRY#SONIC",
      "##TON#OWL#OAR##",
      "PEARL#ASH#NOVEL",
      "OAK#CLIMATE#APE",
      "WEB#LIBRARY#TIN",
      "NET#ECLIPSE#EVE",
      "BRAIN#AGE#STEAL",
      "##RIG#FAN#GEL##",
      "LEMON#OLD#PLUME",
      "OVEN#REIGN#ACID",
      "FIRE#IMAGE#DELI",
      "TORN#NOTES#YELL",
    ],
    acrossClues: [
      "Light source", "Gaze at", "Club sport",
      "Gemstone", "Wading bird", "Concept",
      "Climbing plant", "Precise", "Money owed",
      "Our planet", "Not wet", "Sound-related",
      "Weight unit", "Night bird", "Rowing tool",
      "Oyster gem", "Fireplace dust", "New book",
      "Strong tree", "Weather pattern", "Primate",
      "Spider creation", "Book collection", "Metal can",
      "Mesh fabric", "Sun blockage", "Night before",
      "Thinking organ", "Time period", "Take secretly",
      "Oil platform", "Cooling device", "Hair product",
      "Citrus fruit", "Not new", "Decorative feather",
      "Baking appliance", "Rule", "Sour substance",
      "Blaze", "Reflection", "Sandwich shop",
      "Ripped", "Musical marks", "Shout",
    ],
    downClues: [
      "Column letters", "Vertical chain", "Down pattern",
      "Grid crossing", "Through column", "Cross fill",
      "Letter sequence", "Intersecting", "Down word",
      "Vertical entry", "Linked column", "Column path",
      "Down fill", "Mixed letters", "Crossing point",
      "Column trail", "Cross pattern", "Through path",
      "Vertical line", "Letter column", "Grid fill",
      "Down run", "Column entry", "Down sequence",
      "Cross entry", "Vertical path", "Letter chain",
      "Crossing word", "Column fill",
    ],
  },
  {
    grid: [
      "CAPE#DROWN#LIMB",
      "APEX#IVORY#AREA",
      "RUST#TEETH#GLOW",
      "SIREN#PAD#VOCAL",
      "##TIN#ARC#LOG##",
      "GHOST#RAW#SHELF",
      "AGE#CABINET#ONE",
      "IRE#ORIGAMI#PEN",
      "DIM#TEXTILE#ERA",
      "SPADE#OWL#BRIEF",
      "##APE#BAD#OAK##",
      "OPERA#DAM#MONTH",
      "MAZE#PULSE#IRON",
      "EVEN#ULTRA#MENU",
      "NEST#DELTA#YOGI",
    ],
    acrossClues: [
      "Superhero cloak", "Submerge in water", "Tree branch",
      "Highest point", "Elephant tusk material", "Zone",
      "Corrosion", "Chompers", "Faint light",
      "Warning sound", "Cushion", "Sung aloud",
      "Metal can", "Curved line", "Timber piece",
      "Phantom", "Uncooked", "Storage ledge",
      "Time period", "Furniture piece", "Single",
      "Anger", "Paper folding art", "Writing tool",
      "Faint or dark", "Woven fabric", "Historical period",
      "Digging tool", "Night bird", "Short summary",
      "Primate", "Not good", "Strong tree",
      "Musical drama", "Water barrier", "Calendar unit",
      "Winding puzzle", "Heartbeat", "Metal element",
      "Level", "Extreme", "Food list",
      "Bird home", "River mouth shape", "Meditation practitioner",
    ],
    downClues: [
      "Vertical chain", "Grid crossing", "Down pattern",
      "Cross column", "Letter run", "Intersecting",
      "Column fill", "Through line", "Down word",
      "Vertical path", "Crossing point", "Mixed fill",
      "Linked column", "Down entry", "Column pattern",
      "Grid letters", "Letter path", "Cross pattern",
      "Through column", "Vertical fill", "Down sequence",
      "Column entry", "Grid fill", "Letter column",
      "Down run", "Crossing word", "Column chain",
      "Vertical entry", "Cross entry",
    ],
  },
];
